---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus
#  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus-server
  template:
    metadata:
      labels:
        app: nexus-server
    spec:
      containers:
        - name: nexus
          image: sonatype/nexus3:latest
          securityContext:
            runAsUser: 0
          resources:
            limits:
              memory: "4Gi"
              cpu: "1000m"
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus-data
              mountPath: "/nexus-data"
      volumes:
        - name: nexus-data
          persistentVolumeClaim:
            claimName: nexus-claim

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  labels:
    run: nexus-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: nexus-server
