apiVersion: v1
kind: Service
metadata:
  name: nexus-server
  labels:
    run: nexus-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32081
  selector:
    app: nexus-server

